#pragma once

enum Action {
  INCLINE_FORW,
  INCLINE_BACKW,
  INCLINE_LEFT,
  INCLINE_RIGHT,
  INCLINE_DEFAULT,

  ARM,
  CALIBRATE,

  SET_PITCH_PROP_COEF,
  SET_PITCH_DER_COEF,
  SET_PITCH_INT_COEF,

  SET_ROLL_PROP_COEF,
  SET_ROLL_DER_COEF,
  SET_ROLL_INT_COEF,

  SET_YAW_SP_PROP_COEF,
  SET_YAW_SP_DER_COEF,
  SET_YAW_SP_INT_COEF,

  SET_PITCH_BIAS,
  SET_ROLL_BIAS,
  SET_YAW_SPEED_BIAS,

  SET_BASE_VAL,

  SET_ACC_TRUST,
  SET_INC_CH_RATE_FILTER_COEF,
  SET_YAW_SP_FILTER_COEF,
  SET_YAW_SP_CH_RATE_FILTER_COEF,

  SET_ONLY_POSITIVE_ADJUST_MODE
};

